[build]
buildCommand = "cd ../.. && npm run build"

[deploy]
startCommand = "cd ../.. && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
STACKSLEUTH_SDK_URL = "http://localhost:4000"
STACKSLEUTH_SDK_PORT = "4000"
