[build]
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
STACKSLEUTH_SDK_URL = "http://127.0.0.1:4000"
STACKSLEUTH_SDK_PORT = "4000"
HOSTNAME = "0.0.0.0"
